### PR TITLE
Merge jdk-15-ga

### PR DESCRIPTION
**Pull request by caoman**
Hi all,

This PR is for a merge, and to demonstrate that non-Committer could help on merging/syncing via PRs. The merge is created with `git checkout tsan; git merge --no-ff jdk-15-ga`.

Conflicts/manual changes are:
- Changes in make/autoconf/hotspot.m4 have been reimplemented in make/autoconf/jvm-features.m4.
- In make/autoconf/flags-cflags.m4, `-Os` flag for clang is only applied to aarch64, but not macosx.
- In shenandoahPhaseTimings.hpp, TSANWeakRoots needs to adapt to new format of the SHENANDOAH_PAR_PHASE_DO macro.
- In shenandoahRootProcessor.hpp/cpp, ShenandoahTSANWeakRoot needs a new parameter in the constructor, and _tsan_weak_roots needs to be in ShenandoahSerialWeakRoots's initializer list.
- Conflicts in the following files are trivial. They are simple changes to the patch context:
  - src/hotspot/share/classfile/javaClasses.hpp
  - src/hotspot/share/interpreter/templateTable.cpp
  - src/hotspot/share/runtime/globals.hpp
  - src/hotspot/share/runtime/init.cpp
  - src/hotspot/share/runtime/synchronizer.cpp

Tested with TSAN jtreg tests with LLVM 8.0 (https://releases.llvm.org/download.html#8.0.1). The tests are executed via `$ make test TEST=hotspot/jtreg/tsan`.

We cannot test with LLVM 16.0, because jdk-15-ga itself does not build with LLVM 16.0. Also building bin/java with recent LLVM versions with `-fsanitizer=thread` would cause ThreadSanitizer:DEADLYSIGNAL error at run-time.

-Man

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewers
 * [Jiangli Zhou](https://openjdk.org/census#jiangli) (@jianglizhou - no project role)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/tsan.git pull/15/head:pull/15` \
`$ git checkout pull/15`

Update a local copy of the PR: \
`$ git checkout pull/15` \
`$ git pull https://git.openjdk.org/tsan.git pull/15/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15`

View PR using the GUI difftool: \
`$ git pr show -t 15`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/tsan/pull/15.diff">https://git.openjdk.org/tsan/pull/15.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/tsan/pull/15#issuecomment-1696149476)

### CODE REVIEW

**Comment by caoman** [comment]
@jianglizhou I have updated the description to mention details of the resolved conflicts, as well as commands for the merge and running tests.

Could you take a look?

**Comment by jianglizhou** [comment]
@caoman and I did a walk-through of his merge changes in this PR today. We went through all hand merged changes in details to make sure:

- no missed TSAN work during hand merge

LGTM for the merge work.

**Review by jianglizhou — APPROVED** [review]
@caoman and I did a walk-through of his merge changes in this PR today. We went through all hand merged changes in details to make sure:

no missed TSAN work during hand merge
LGTM for the merge work.

**Comment by caoman** [comment]
Thanks for the review!

**Pull request closed without merging**
