### PR TITLE
Merge jdk-17-ga

### PR DESCRIPTION
**Pull request by jianglizhou**
Command: `$ git merge --no-ff jdk-17-ga`

Most manual merge for conflicts are mechanical.

Additional manual updates:

- Add `#include "memory/resourceArea.hpp"` in src/hotspot/share/tsan/tsanOopMap.cpp to resolve compiler error:

tsanOopMap.cpp:351:5: error: use of undeclared identifier 'ResourceMark'; did you mean 'ResourceStack'?
    ResourceMark rm;
    ^~~~~~~~~~~~
    ResourceStack

- Remove `AMD64_ONLY(assert((id_u8 & left_n_bits(17)) == 0, "jmethodID is not aligned");)` in classFileParser.cpp. `left_n_bits` has been removed by https://bugs.openjdk.org/browse/JDK-8178348

- Change `obj_field_addr_raw<oop>()` to `field_addr()` in java_lang_Class::init_lock_addr in javaClasses.cpp.

- Remove `ShenandoahTSANWeakRoot::ShenandoahTSANWeakRoot` as `ShenandoahWeakSerialRoot` is removed in shenandoahPhaseTimings.hpp.

- Remove JVMWrapper calls in tsan related functions in jvm.cpp. The macro has been removed.

- Change to use `current` for `JRT_ENTRY(void, SharedRuntime::tsan_interp_method_entry(JavaThread* thread))` as JRT_ENTRY macro expects `current`, sharedRuntime.cpp.

- Change `THREAD` to `current` in synchronizer.cpp.

Tested by running hotspot/jtreg/tsan locally:

```
$ bash configure --with-boot-jdk=$HOME/openjdk/jdk-17.0.10 --with-debug-level=release--disable-warnings-as-errors --with-jtreg=$HOME/github/jtreg/build/images/jtreg --with-stdc++lib=static --disable-precompiled-headers --enable-unlimited-crypto --with-native-debug-symbols=internal --with-default-make-target=jdk-image --disable-warnings-as-errors --with-toolchain-type=clang --with-toolchain-path=$HOME/clang+llvm-8.0.1-amd64-unknown-freebsd11 --disable-warnings-as-errors


$ make test TEST=hotspot/jtreg/tsan
```

tsan/NonRacySyncBlockExceptionLoopTest.java fails. All other tests pass.

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Error
&nbsp;⚠️ A merge PR must contain at least one commit from the source branch that is not already present in the target.

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/tsan.git pull/16/head:pull/16` \
`$ git checkout pull/16`

Update a local copy of the PR: \
`$ git checkout pull/16` \
`$ git pull https://git.openjdk.org/tsan.git pull/16/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 16`

View PR using the GUI difftool: \
`$ git pr show -t 16`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/tsan/pull/16.diff">https://git.openjdk.org/tsan/pull/16.diff</a>

</details>

### CODE REVIEW

**Comment by caoman** [comment]
Could you rename the title to "Merge jdk-17-ga"? This should fix the jcheck error.
Hopefully renaming the title also makes Github show each merged commit, instead of a single huge commit.

**Comment by jianglizhou** [comment]
> Could you rename the title to "Merge jdk-17-ga"? This should fix the jcheck error. Hopefully renaming the title also makes Github show each merged commit, instead of a single huge commit.

Done.

**Comment by jianglizhou** [comment]
> > Could you rename the title to "Merge jdk-17-ga"? This should fix the jcheck error. Hopefully renaming the title also makes Github show each merged commit, instead of a single huge commit.
> 
> Done.

Looks like that didn't help. The jcheck failed with "A merge PR must contain at least one commit from the source branch that is not already present in the target".

Using `$ git log` in my local tsan branch, I don't see the commits brought in by the merge.

**Comment by caoman** [comment]
In description, shenandoahPhaseTimings.hpp should probably be shenandoahRootProcessor.hpp.

Per discussion with Jiangli, Jiangli will try creating another PR that shows each merged commit, instead of a single huge commit.

**Comment by caoman** [comment]
I downloaded the PR, and it seems that adding a parent commit will fix the single huge commit problem:
```
$ git replace --graft b555da6b7270b21aadb41e77e3f0f72f67f5704e 8fe80f4e6d9f8bd358dba5178422de0743b0b3ff jdk-17-ga
```

It is also OK to redo the merge from the beginning and create a new PR, if you suspect something else is wrong.

**Comment by jianglizhou** [comment]
> In description, shenandoahPhaseTimings.hpp should probably be shenandoahRootProcessor.hpp.

Will fix in the new PR description.

> 
> Per discussion with Jiangli, Jiangli will try creating another PR that shows each merged commit, instead of a single huge commit.

@caoman, thanks for looking into the merge commit issue!

**Comment by jianglizhou** [comment]
> > In description, shenandoahPhaseTimings.hpp should probably be shenandoahRootProcessor.hpp.
> 
> Will fix in the new PR description.
> 
> > Per discussion with Jiangli, Jiangli will try creating another PR that shows each merged commit, instead of a single huge commit.
> 
> @caoman, thanks for looking into the merge commit issue!

@caoman and I looked more into this. We've found that the commit issue was due to a branch created after the merge in my process. I created a fresh https://github.com/openjdk/tsan/pull/17 for jdk-17-ga merge.

**Pull request closed without merging**
