### PR TITLE
Merge jdk21u

### PR DESCRIPTION
**Pull request by jianglizhou**
This PR merges with JDK 21.0.3 (https://github.com/openjdk/jdk/commit/05f18b10620834883180013bb8873a6b4bdc6df2).

Merge was done most automatically. See manual edit and change details below.

**Manual changes:**
- Edited `.jcheck/conf` and `src/hotspot/share/logging/logTag.hpp` to resolve trivial merge conflicts.
- Changed `TsanRunner `to use `ProcessTools.createLimitedTestJavaProcessBuilder()` to resolve tsan jtreg test failures. `ProcessTools.createJavaProcessBuilder()` was renamed to `ProcessTools.createLimitedTestJavaProcessBuilder` by https://github.com/openjdk/jdk/pull/15452.

**Merge commands:**
```
$ git remote add 21u https://github.com/openjdk/jdk21u.git
$ git remote update
$ git merge 05f18b1
#resolve merge conflicts and commit
$ git remote remove 21u
```

**Testing:**
```
$ bash configure --with-boot-jdk=/usr/local/google/home/jianglizhou/openjdk/jdk-21.0.1 --with-debug-level=release --disable-warnings-as-errors --with-jtreg=/usr/local/google/home/jianglizhou/github/jtreg/build/images/jtreg --with-stdc++lib=static --disable-precompiled-headers --enable-unlimited-crypto --with-native-debug-symbols=internal --with-default-make-target=jdk-image --disable-warnings-as-errors --with-toolchain-type=clang --disable-warnings-as-errors
```

```
$ make test TEST=hotspot/jtreg/tsan
```
All tests pass with `release` binary
```
==============================
Test summary
==============================
   TEST                                              TOTAL  PASS  FAIL ERROR   
   jtreg:test/hotspot/jtreg/tsan                        79    79     0     0   
==============================
TEST SUCCESS
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/tsan.git pull/21/head:pull/21` \
`$ git checkout pull/21`

Update a local copy of the PR: \
`$ git checkout pull/21` \
`$ git pull https://git.openjdk.org/tsan.git pull/21/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21`

View PR using the GUI difftool: \
`$ git pr show -t 21`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/tsan/pull/21.diff">https://git.openjdk.org/tsan/pull/21.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/tsan/pull/21#issuecomment-2259333931)

### CODE REVIEW

**Comment by caoman** [comment]
Thank you for the merge.
Could we create a new branch (e.g. "tsan-21u") in the TSAN project to track TSAN based on JDK 21u? The current "tsan" branch in intended to track OpenJDK's tip.

**Comment by jianglizhou** [comment]
> Could we create a new branch (e.g. "tsan-21u") in the TSAN project to track TSAN based on JDK 21u? The current "tsan" branch in intended to track OpenJDK's tip.

SG for creating tsan-21u branch.

**Comment by caoman** [comment]
> > Could we create a new branch (e.g. "tsan-21u") in the TSAN project to track TSAN based on JDK 21u? The current "tsan" branch in intended to track OpenJDK's tip.
> 
> SG for creating tsan-21u branch.

Asked in https://bugs.openjdk.org/browse/SKARA-2345 to allow creating new branches.

**Comment by jianglizhou** [comment]
> > Could we create a new branch (e.g. "tsan-21u") in the TSAN project to track TSAN based on JDK 21u? The current "tsan" branch in intended to track OpenJDK's tip.
> 
> SG for creating tsan-21u branch.

An alternative is to only track the JDK mainline and not track any of the JDK update repo. That can avoid complications with handling branches. Let me try integrate the current tsan repo internally.

For JDK 21, there is a bit delay. For future JDK LTS/STS integrations, we can integrate them to the tsan repo sooner after a `ga` release.

**Comment by jianglizhou** [comment]
> > > Could we create a new branch (e.g. "tsan-21u") in the TSAN project to track TSAN based on JDK 21u? The current "tsan" branch in intended to track OpenJDK's tip.
> > 
> > 
> > SG for creating tsan-21u branch.
> 
> An alternative is to only track the JDK mainline and not track any of the JDK update repo. That can avoid complications with handling branches. Let me try integrate the current tsan repo internally.
> 
> For JDK 21, there is a bit delay. For future JDK LTS/STS integrations, we can integrate them to the tsan repo sooner after a `ga` release.

I tried integrating the current tsan changes (based on `jdk-21-ga`) with a JDK code base mirroring JDK 21.0.3. The integration went smoothly. `TsanRunner` needed the `ProcessTools.createLimitedTestJavaProcessBuilder()` change, otherwise there were no significant integration issues. So tracking with the JDK mainline is quite practical. It avoids the complications with managing branches related to tracking JDK update repo.

I'll close the PR based on the above.

**Pull request closed without merging**
