### PR TITLE
Merge jdk-17-ga

### PR DESCRIPTION
**Pull request by jianglizhou**
This is a redo of https://github.com/openjdk/tsan/pull/16 to address the commits issue. Updated description:

Command: $ git merge --no-ff jdk-17-ga

Most manual merge for conflicts are mechanical.

Additional manual updates:

Add #include "memory/resourceArea.hpp" in src/hotspot/share/tsan/tsanOopMap.cpp to resolve compiler error:
tsanOopMap.cpp:351:5: error: use of undeclared identifier 'ResourceMark'; did you mean 'ResourceStack'?
ResourceMark rm;
^~~~~~~~~~~~
ResourceStack

Remove AMD64_ONLY(assert((id_u8 & left_n_bits(17)) == 0, "jmethodID is not aligned");) in classFileParser.cpp. left_n_bits has been removed by https://bugs.openjdk.org/browse/JDK-8178348

Change obj_field_addr_raw<oop>() to field_addr() in java_lang_Class::init_lock_addr in javaClasses.cpp.

Remove ShenandoahTSANWeakRoot::ShenandoahTSANWeakRoot as ShenandoahWeakSerialRoot is removed in shenandoahRootProcessor.cpp.

Remove JVMWrapper calls in tsan related functions in jvm.cpp. The macro has been removed.

Change to use current for JRT_ENTRY(void, SharedRuntime::tsan_interp_method_entry(JavaThread* thread)) as JRT_ENTRY macro expects current, sharedRuntime.cpp.

Change THREAD to current in synchronizer.cpp.

Updated test/hotspot/jtreg/runtime/StackGuardPages/exeinvoke.c to merge JDK-8272472 change to avoid build failure for testing.

Tested by running hotspot/jtreg/tsan locally:

```
$ bash configure --with-boot-jdk=/usr/local/google/home/jianglizhou/openjdk/jdk-17.0.10 --with-debug-level=release --disable-warnings-as-errors --with-jtreg=/usr/local/google/home/jianglizhou/github/jtreg/build/images/jtreg --with-stdc++lib=static --disable-precompiled-headers --enable-unlimited-crypto --with-native-debug-symbols=internal --with-default-make-target=jdk-image --disable-warnings-as-errors --with-toolchain-type=clang --with-toolchain-path=/usr/local/google/home/jianglizhou/clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04 --disable-warnings-as-errors

$ make test TEST=hotspot/jtreg/tsan
```
Tsan is not fully functional with jdk-17 merge. New runs found more random failures in addition to tsan/NonRacySyncBlockExceptionLoopTest.java. The failed tests appear to be inconsistent, but tsan/NonRacyGarbageCollectionLoopTest.java is more consistently failing. The test failures most likely is because there is no longer serial iterator for the TsanOopMap. 

Also built and tested using Clang/LLVM 16.0.6. It appears to be working with jdk-17-ga merge.

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewers
 * [Man Cao](https://openjdk.org/census#manc) (@caoman - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/tsan.git pull/17/head:pull/17` \
`$ git checkout pull/17`

Update a local copy of the PR: \
`$ git checkout pull/17` \
`$ git pull https://git.openjdk.org/tsan.git pull/17/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17`

View PR using the GUI difftool: \
`$ git pr show -t 17`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/tsan/pull/17.diff">https://git.openjdk.org/tsan/pull/17.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/tsan/pull/17#issuecomment-1949396012)

### CODE REVIEW

**Comment by jianglizhou** [comment]
I checked tsan specific changes in original src/hotspot/share/gc/shared/weakProcessorPhases.cpp and src/hotspot/share/gc/shared/weakProcessorPhases.hpp. The tsan specific changes in those are no longer applicable. https://bugs.openjdk.org/browse/JDK-8212879 made JVMTI tagmap table  walked by GC concurrently, and the serial iterator was removed. I think the tsan test failures that I encountered with 17 merge was related to tagmap change. 

@caoman We can move forward with the review for the jdk 17 merge. I'll do some study on the JDK-8212879 to see how to include the handling for TsanOopMap.

**Comment by caoman** [comment]
Agree that it is better to adapt TsanOopMap in a separate PR. Another reference is https://bugs.openjdk.org/browse/JDK-8235573, which moved `JFR::weak_oops_do` to use OopStorage and support concurrent processing.

Could you update the description to mention that after this merge, TSAN is not yet fully working? This is because `TsanOopMap::weak_oops_do()` is not called anywhere, so TSAN fails to keep track of objects moved by GC. 

A few comments:
1. In .jcheck/conf, could we use JDK 17's lines for `error=` and `files=`?
2. In src/hotspot/share/classfile/systemDictionary.cpp, line `assert(calledholdinglock,"must hold lock for notify");` seems an accidental removal of space.
3. The changes to shenandoahPhaseTimings.hpp, shenandoahRootProcessor.hpp/cpp look unnecessary. It seems to revive removed classes `ShenandoahSerialRoot`, `ShenandoahWeakSerialRoot`, `ShenandoahSerialWeakRoots`, etc, I think we can drop these changes to shenandoah files similarly to dropping the TSAN changes to weakProcessorPhases.cpp and weakProcessorPhases.hpp. They are all related to `TsanOopMap`, and the TSAN-touched Shenandoah classes no longer exist in JDK 17.
4. In src/hotspot/share/runtime/globals.hpp, there is a missing empty line between the `ThreadSanitizerIgnoreFile` flag and the later `VerifyCrossModifyFence` flag.
5. In src/hotspot/share/runtime/synchronizer.cpp for `ObjectSynchronizer::wait()`, the change to `DTRACE_MONITOR_WAIT_PROBE` line seems unnecessary.
6. The change to test/hotspot/jtreg/runtime/StackGuardPages/exeinvoke.c seems a backport of https://bugs.openjdk.org/browse/JDK-8272472. Perhaps mention this in description?

**Comment by jianglizhou** [comment]
Thanks for the careful review!

> Agree that it is better to adapt TsanOopMap in a separate PR. Another reference is https://bugs.openjdk.org/browse/JDK-8235573, which moved `JFR::weak_oops_do` to use OopStorage and support concurrent processing.
> 
> Could you update the description to mention that after this merge, TSAN is not yet fully working? This is because `TsanOopMap::weak_oops_do()` is not called anywhere, so TSAN fails to keep track of objects moved by GC.

Done.

> 
> A few comments:
> 
> 1. In .jcheck/conf, could we use JDK 17's lines for `error=` and `files=`?

Applied.

> 2. In src/hotspot/share/classfile/systemDictionary.cpp, line `assert(calledholdinglock,"must hold lock for notify");` seems an accidental removal of space.

Added space. The line without space was from the jdk-15 version.

> 3. The changes to shenandoahPhaseTimings.hpp, shenandoahRootProcessor.hpp/cpp look unnecessary. It seems to revive removed classes `ShenandoahSerialRoot`, `ShenandoahWeakSerialRoot`, `ShenandoahSerialWeakRoots`, etc, I think we can drop these changes to shenandoah files similarly to dropping the TSAN changes to weakProcessorPhases.cpp and weakProcessorPhases.hpp. They are all related to `TsanOopMap`, and the TSAN-touched Shenandoah classes no longer exist in JDK 17.

Removed.

> 4. In src/hotspot/share/runtime/globals.hpp, there is a missing empty line between the `ThreadSanitizerIgnoreFile` flag and the later `VerifyCrossModifyFence` flag.

Added empty line.

> 5. In src/hotspot/share/runtime/synchronizer.cpp for `ObjectSynchronizer::wait()`, the change to `DTRACE_MONITOR_WAIT_PROBE` line seems unnecessary.

Changed `THREAD` to `current` (current is set to THREAD). `THREAD` was from the jdk-15 version.

> 6. The change to test/hotspot/jtreg/runtime/StackGuardPages/exeinvoke.c seems a backport of https://bugs.openjdk.org/browse/JDK-8272472. Perhaps mention this in description?

Done.

**Comment by caoman** [comment]
Looks good, thank you!

**Review by caoman — APPROVED** [review]

**Comment by jianglizhou** [comment]
@caoman Can you please try sponsor? Looks like that might be needed as I'm not a committer for tsan project. Thanks

> As you do not have [Committer](https://openjdk.org/bylaws#committer) status in [this project](https://openjdk.org/census#tsan) an existing Committer must agree to [sponsor](https://openjdk.org/sponsor/) your change.

**Comment by zhaosongzs** [comment]
Hi @jianglizhou , could you please issue /integrate again?

**Comment by caoman** [comment]
Thank you @zhaosongzs, this was integrated successfully.

**Comment by jianglizhou** [comment]
Thank you, @zhaosongzs!

**Comment by zhaosongzs** [comment]
To test SKARA-2190, I am adding this comment to update this pull request.
This comment can be safely ignored.

**Pull request closed without merging**
